name: drp_core
version: '${project.version}'
main: ml.jozo.drp_core.Drp_core
api-version: 1.19
authors: [Jozo_85]
description: Plugin for Diveregence 
website: divergencerp.ml
commands:
  fly:
    description: Příkaz na zapnutí létání
    usage: /fly
    aliases: f
    permission: fly
    permission-message: Nemáš práva
